blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.all_blogs, name='all_blogs'),

    # Redirect old ID-based URLs to slug URLs
    path("<int:id>/", views.redirect_to_slug, name='blog-redirect'),

    # New slug-based URL for blog details
    path("<slug:slug>/", views.detail, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.sitemaps.views import sitemap
from listings.sitemaps import ListingSitemap
from pages.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.views.generic.base import TemplateView

handler404 = 'pages.views.handler404'

sitemaps = {
    "static": StaticViewSitemap(),
    "listings": ListingSitemap(),
    'blog': BlogSitemap(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('listings/',include('listings.urls')),
    path('accounts/',include('accounts.urls')),
    path('contacts/',include('contacts.urls')),
    path('blogs/',include('blog.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('sitemap-listings.xml', sitemap, {'sitemaps': {'listings': ListingSitemap}}, name='sitemap-listings'),
    path('sitemap-blogs.xml', sitemap, {'sitemaps': {'blogs': BlogSitemap}}, name='sitemap-blogs'),
    path('googleef77926a2a0da1fa.html', TemplateView.as_view(template_name="googleef77926a2a0da1fa.html", content_type="text/html")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.tags == 'error' %}
                        Error:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

<script>
    setTimeout(function() {
        $(".alert").fadeOut("slow");
    }, 3000);
</script>

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> JeyaSakthi Real Estate
</footer>

<!-- WhatsApp Floating Button -->
<a href="https://wa.me/916369032050" class="whatsapp-float" target="_blank">
    <img src="https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg" alt="WhatsApp" width="50">
</a>

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
<div class="container">
<a class="navbar-brand" href="{% url 'index' %}">
    <img src="{% static 'img/logo.png' %}" class="logo" alt="">
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
        <li 
        {% if '/' == request.path %}
            class="nav-item active mr-3"
        {% else %}
            class="nav-item mr-3"
        {% endif %}
        >
            <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li 
        {% if 'about' in request.path %}
            class="nav-item active mr-3"
        {% else %}
            class="nav-item mr-3"
        {% endif %}
        >
            <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li 
        {% if 'listings' in request.path %}
            class="nav-item active mr-3"
        {% else %}
            class="nav-item mr-3"
        {% endif %}
        >
            <a class="nav-link" href="{% url 'listings' %}">Featured Listings</a>
        </li>
        <!-- Blog Section -->
        <li 
        {% if 'blogs' in request.path %}
            class="nav-item active mr-3"
        {% else %}
            class="nav-item mr-3"
        {% endif %}
        >
            <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a>
        </li>

    </ul>
    

    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li 
            {% if 'dashboard' in request.path %}
                class="nav-item active mr-3"
            {% else %}
                class="nav-item mr-3"
            {% endif %}>
                <a class="nav-link" href="{% url 'dashboard' %}">
                Welcome {{ user.username | title }} (Dashboard) </a>
            </li>

            <li class="nav-item mr-3">
                <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link"><i class="fas fa-sign-out-alt"></i>Logout</a>
                <form action="{% url 'logout' %}" id="logout" method="POST">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            </li>
        {% else %}
            <li 
            {% if 'register' in request.path %}
                class="nav-item active mr-3"
            {% else %}
                class="nav-item mr-3"
            {% endif %}>
                <a class="nav-link" href="{% url 'register' %}">
                <i class="fas fa-user-plus"></i> Register</a>
            </li>
            <li 
            {% if 'login' in request.path %}
                class="nav-item active mr-3"
            {% else %}
                class="nav-item mr-3"
            {% endif %}>
                <a class="nav-link" href="{% url 'login' %}">
                <i class="fas fa-sign-in-alt"></i>

                Login</a>
            </li>
        {% endif %}
    </ul>
</div>
</div>
</nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fas fa-phone"></i> 
                <a href="tel:+916369032050">+91 6369032050</a>
            </div>
            <div class="col-md-4">
                <i class="fas fa-envelope-open"></i> 
                <a href="mailto:jeyasakthi0528@gmail.com">jeyasakthi0528@gmail.com</a>
            </div>
            <div class="col-md-4">
                <div class="social text-right">
                    <a href="https://x.com/JeyaSakthiHomes"><i class="fab fa-x-twitter"></i></a>
                    <a href="https://www.facebook.com/profile.php?id=61579135361710"><i class="fab fa-facebook"></i></a>
                    <a href="#"><i class="fab fa-linkedin"></i></a>
                    <a href="https://www.instagram.com/jeyasakthirealestate"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>